using System;
using System.Collections.Generic;
using UnityEngine;
#if UNITY_EDITOR
using UnityEditor;
#endif

namespace RecycleVision
{
    [Serializable]
    public class WasteItemDefinition
    {
        [SerializeField] private string id;
        [SerializeField] private string displayName;
        [SerializeField] private RecycleCategory correctBin;
        [SerializeField] private RecycleCategory commonMistakeBin;
        [SerializeField] private WasteVisualShape visualShape;
        [SerializeField] private Color primaryColor = Color.white;
        [SerializeField] private Color accentColor = Color.gray;
        [SerializeField] private float scale = 1f;
        [SerializeField] private float baseAiConfidence = 0.85f;
        [SerializeField] private float confusionChance = 0.15f;
        [SerializeField] [TextArea(2, 4)] private string trainingHint;
        [SerializeField] private GameObject visualPrefab;
        [SerializeField] private Vector3 visualPrefabOffset = Vector3.zero;
        [SerializeField] private Vector3 visualPrefabEuler = Vector3.zero;
        [SerializeField] private Vector3 visualPrefabScale = Vector3.one;

        public string Id => id;
        public string DisplayName => displayName;
        public RecycleCategory CorrectBin => correctBin;
        public RecycleCategory CommonMistakeBin => commonMistakeBin;
        public WasteVisualShape VisualShape => visualShape;
        public Color PrimaryColor => primaryColor;
        public Color AccentColor => accentColor;
        public float Scale => scale;
        public float BaseAiConfidence => baseAiConfidence;
        public float ConfusionChance => confusionChance;
        public string TrainingHint => trainingHint;
        public GameObject VisualPrefab => visualPrefab;
        public Vector3 VisualPrefabOffset => visualPrefabOffset;
        public Vector3 VisualPrefabEuler => visualPrefabEuler;
        public Vector3 VisualPrefabScale => visualPrefabScale;

        public WasteItemDefinition(
            string id,
            string displayName,
            RecycleCategory correctBin,
            RecycleCategory commonMistakeBin,
            WasteVisualShape visualShape,
            Color primaryColor,
            Color accentColor,
            float scale,
            float baseAiConfidence,
            float confusionChance,
            string trainingHint,
            GameObject visualPrefab = null,
            Vector3? visualPrefabOffset = null,
            Vector3? visualPrefabEuler = null,
            Vector3? visualPrefabScale = null)
        {
            this.id = id;
            this.displayName = displayName;
            this.correctBin = correctBin;
            this.commonMistakeBin = commonMistakeBin;
            this.visualShape = visualShape;
            this.primaryColor = primaryColor;
            this.accentColor = accentColor;
            this.scale = scale;
            this.baseAiConfidence = baseAiConfidence;
            this.confusionChance = confusionChance;
            this.trainingHint = trainingHint;
            this.visualPrefab = visualPrefab;
            this.visualPrefabOffset = visualPrefabOffset ?? Vector3.zero;
            this.visualPrefabEuler = visualPrefabEuler ?? Vector3.zero;
            this.visualPrefabScale = visualPrefabScale ?? Vector3.one;
        }

        public static List<WasteItemDefinition> CreateDefaults()
        {
            return new List<WasteItemDefinition>
            {
                new WasteItemDefinition(
                    "plastic_bottle",
                    "Plastic Bottle",
                    RecycleCategory.Plastic,
                    RecycleCategory.Glass,
                    WasteVisualShape.Bottle,
                    new Color(0.46f, 0.85f, 0.97f),
                    new Color(0.07f, 0.39f, 0.77f),
                    1f,
                    0.92f,
                    0.08f,
                    "Empty and rinse the bottle, then place it in the plastic bin.",
                    LoadPrefab("Assets/ithappy/Food_FREE/Prefabs/drink_001.prefab"),
                    Vector3.zero,
                    Vector3.zero,
                    Vector3.one * 0.78f),
                new WasteItemDefinition(
                    "yogurt_cup",
                    "Yogurt Cup",
                    RecycleCategory.Plastic,
                    RecycleCategory.PaperCardboard,
                    WasteVisualShape.Cup,
                    new Color(0.91f, 0.91f, 0.96f),
                    new Color(0.93f, 0.36f, 0.48f),
                    0.92f,
                    0.81f,
                    0.16f,
                    "Small food containers still count as plastic after they are emptied.",
                    LoadPrefab("Assets/ithappy/Food_FREE/Prefabs/yogurt_001.prefab"),
                    Vector3.zero,
                    Vector3.zero,
                    Vector3.one * 0.8f),
                new WasteItemDefinition(
                    "cereal_box",
                    "Cereal Box",
                    RecycleCategory.PaperCardboard,
                    RecycleCategory.Plastic,
                    WasteVisualShape.Box,
                    new Color(0.82f, 0.66f, 0.39f),
                    new Color(0.59f, 0.32f, 0.13f),
                    1.08f,
                    0.88f,
                    0.09f,
                    "Clean cardboard packaging belongs in the paper / cardboard bin.",
                    LoadPrefab("Assets/GVOZDY/Cardboard Boxes with Tape/Prefabs/box_1_brownTape.prefab"),
                    Vector3.zero,
                    Vector3.zero,
                    Vector3.one * 0.34f),
                new WasteItemDefinition(
                    "newspaper_bundle",
                    "Newspaper Bundle",
                    RecycleCategory.PaperCardboard,
                    RecycleCategory.Organic,
                    WasteVisualShape.FlatPack,
                    new Color(0.83f, 0.83f, 0.8f),
                    new Color(0.58f, 0.58f, 0.56f),
                    1.03f,
                    0.9f,
                    0.06f,
                    "Dry paper stacks go with paper and cardboard, not organic waste.",
                    LoadPrefab("Assets/DanielRiches/BooksEssentials/Prefabs/Book3.prefab"),
                    Vector3.zero,
                    new Vector3(0f, 90f, 0f),
                    Vector3.one * 0.46f),
                new WasteItemDefinition(
                    "glass_jar",
                    "Glass Jar",
                    RecycleCategory.Glass,
                    RecycleCategory.Plastic,
                    WasteVisualShape.Jar,
                    new Color(0.61f, 0.9f, 0.82f),
                    new Color(0.2f, 0.58f, 0.48f),
                    0.96f,
                    0.9f,
                    0.07f,
                    "Glass jars belong in the glass bin once the contents are removed.",
                    LoadPrefab("Assets/LowpolyDrinkGlasses/Prefabs/Collection_2.prefab"),
                    Vector3.zero,
                    Vector3.zero,
                    Vector3.one * 0.18f),
                new WasteItemDefinition(
                    "glass_bottle",
                    "Glass Bottle",
                    RecycleCategory.Glass,
                    RecycleCategory.Plastic,
                    WasteVisualShape.Bottle,
                    new Color(0.35f, 0.69f, 0.41f),
                    new Color(0.12f, 0.25f, 0.13f),
                    1.06f,
                    0.9f,
                    0.08f,
                    "Glass keeps its own stream so it should not be mixed into plastic.",
                    LoadPrefab("Assets/LowpolyDrinkGlasses/Prefabs/Collection_4.prefab"),
                    Vector3.zero,
                    Vector3.zero,
                    Vector3.one * 0.18f),
                new WasteItemDefinition(
                    "apple_core",
                    "Apple Core",
                    RecycleCategory.Organic,
                    RecycleCategory.PaperCardboard,
                    WasteVisualShape.Scrap,
                    new Color(0.78f, 0.43f, 0.17f),
                    new Color(0.31f, 0.58f, 0.16f),
                    0.85f,
                    0.87f,
                    0.08f,
                    "Food scraps and peelings go to the organic bin.",
                    LoadPrefab("Assets/ithappy/Food_FREE/Prefabs/apple_001.prefab"),
                    Vector3.zero,
                    Vector3.zero,
                    Vector3.one * 0.82f),
                new WasteItemDefinition(
                    "banana_peel",
                    "Banana Peel",
                    RecycleCategory.Organic,
                    RecycleCategory.PaperCardboard,
                    WasteVisualShape.Scrap,
                    new Color(0.93f, 0.84f, 0.2f),
                    new Color(0.44f, 0.31f, 0.15f),
                    1.02f,
                    0.89f,
                    0.07f,
                    "Organic waste stays separate because it can be composted or processed.",
                    LoadPrefab("Assets/ithappy/Food_FREE/Prefabs/banana_001.prefab"),
                    Vector3.zero,
                    new Vector3(0f, 20f, 0f),
                    Vector3.one * 0.88f),
                new WasteItemDefinition(
                    "egg_shells",
                    "Egg Shells",
                    RecycleCategory.Organic,
                    RecycleCategory.Glass,
                    WasteVisualShape.Scrap,
                    new Color(0.95f, 0.92f, 0.83f),
                    new Color(0.71f, 0.62f, 0.55f),
                    0.78f,
                    0.79f,
                    0.19f,
                    "Even brittle food leftovers still count as organic material.",
                    LoadPrefab("Assets/ithappy/Food_FREE/Prefabs/eggplant_001.prefab"),
                    Vector3.zero,
                    Vector3.zero,
                    Vector3.one * 0.74f),
                new WasteItemDefinition(
                    "drink_carton",
                    "Drink Carton",
                    RecycleCategory.PaperCardboard,
                    RecycleCategory.Plastic,
                    WasteVisualShape.Box,
                    new Color(0.89f, 0.95f, 0.98f),
                    new Color(0.15f, 0.45f, 0.87f),
                    0.98f,
                    0.75f,
                    0.2f,
                    "Drink cartons are commonly sorted with paper and cardboard in this setup.",
                    LoadPrefab("Assets/GVOZDY/Cardboard Boxes with Tape/Prefabs/box_2_greyTape.prefab"),
                    Vector3.zero,
                    Vector3.zero,
                    Vector3.one * 0.32f),
                new WasteItemDefinition(
                    "mixed_wrapper",
                    "Mixed Wrapper",
                    RecycleCategory.Plastic,
                    RecycleCategory.PaperCardboard,
                    WasteVisualShape.FlatPack,
                    new Color(0.72f, 0.38f, 0.91f),
                    new Color(0.98f, 0.78f, 0.21f),
                    0.95f,
                    0.63f,
                    0.34f,
                    "This one is tricky: the plastic-like wrapper goes in the plastic bin here.",
                    LoadPrefab("Assets/ithappy/Food_FREE/Prefabs/chips_001.prefab"),
                    Vector3.zero,
                    new Vector3(0f, 40f, 0f),
                    Vector3.one * 0.7f),
                new WasteItemDefinition(
                    "plastic_sports_drink",
                    "Sports Drink Bottle",
                    RecycleCategory.Plastic,
                    RecycleCategory.Glass,
                    WasteVisualShape.Bottle,
                    new Color(0.44f, 0.82f, 0.98f),
                    new Color(0.08f, 0.32f, 0.7f),
                    0.98f,
                    0.9f,
                    0.1f,
                    "Plastic beverage bottles go in the plastic bin after they are emptied.",
                    LoadPrefab("Assets/ithappy/Food_FREE/Prefabs/drink_002.prefab"),
                    Vector3.zero,
                    Vector3.zero,
                    Vector3.one * 0.78f),
                new WasteItemDefinition(
                    "plastic_soda_bottle",
                    "Soda Bottle",
                    RecycleCategory.Plastic,
                    RecycleCategory.Glass,
                    WasteVisualShape.Bottle,
                    new Color(0.9f, 0.45f, 0.43f),
                    new Color(0.62f, 0.17f, 0.2f),
                    0.98f,
                    0.88f,
                    0.12f,
                    "Sort plastic drink bottles into the plastic stream once rinsed.",
                    LoadPrefab("Assets/ithappy/Food_FREE/Prefabs/drink_003.prefab"),
                    Vector3.zero,
                    Vector3.zero,
                    Vector3.one * 0.78f),
                new WasteItemDefinition(
                    "paperback_book",
                    "Paperback Book",
                    RecycleCategory.PaperCardboard,
                    RecycleCategory.Organic,
                    WasteVisualShape.FlatPack,
                    new Color(0.84f, 0.8f, 0.72f),
                    new Color(0.52f, 0.43f, 0.36f),
                    1.02f,
                    0.86f,
                    0.1f,
                    "Books and paperbacks go with paper and cardboard when clean and dry.",
                    LoadPrefab("Assets/DanielRiches/BooksEssentials/Prefabs/Book1.prefab"),
                    Vector3.zero,
                    new Vector3(0f, 90f, 0f),
                    Vector3.one * 0.46f),
                new WasteItemDefinition(
                    "library_book",
                    "Library Book",
                    RecycleCategory.PaperCardboard,
                    RecycleCategory.Organic,
                    WasteVisualShape.FlatPack,
                    new Color(0.76f, 0.72f, 0.66f),
                    new Color(0.42f, 0.36f, 0.3f),
                    1.03f,
                    0.86f,
                    0.1f,
                    "Hardcover books still sort with paper and cardboard in this setup.",
                    LoadPrefab("Assets/DanielRiches/BooksEssentials/Prefabs/Book2.prefab"),
                    Vector3.zero,
                    new Vector3(0f, 90f, 0f),
                    Vector3.one * 0.46f),
                new WasteItemDefinition(
                    "cardboard_box_grey",
                    "Shipping Box (Grey Tape)",
                    RecycleCategory.PaperCardboard,
                    RecycleCategory.Plastic,
                    WasteVisualShape.Box,
                    new Color(0.74f, 0.62f, 0.42f),
                    new Color(0.55f, 0.42f, 0.24f),
                    1.02f,
                    0.86f,
                    0.12f,
                    "Cardboard boxes belong in the paper / cardboard stream.",
                    LoadPrefab("Assets/GVOZDY/Cardboard Boxes with Tape/Prefabs/box_1_greyTape.prefab"),
                    Vector3.zero,
                    Vector3.zero,
                    Vector3.one * 0.34f),
                new WasteItemDefinition(
                    "cardboard_box_brown",
                    "Shipping Box (Brown Tape)",
                    RecycleCategory.PaperCardboard,
                    RecycleCategory.Plastic,
                    WasteVisualShape.Box,
                    new Color(0.76f, 0.56f, 0.34f),
                    new Color(0.58f, 0.4f, 0.2f),
                    1.02f,
                    0.86f,
                    0.12f,
                    "Flatten clean boxes when possible and sort them with cardboard.",
                    LoadPrefab("Assets/GVOZDY/Cardboard Boxes with Tape/Prefabs/box_2_brownTape.prefab"),
                    Vector3.zero,
                    Vector3.zero,
                    Vector3.one * 0.32f),
                new WasteItemDefinition(
                    "glass_goblet",
                    "Glass Goblet",
                    RecycleCategory.Glass,
                    RecycleCategory.Plastic,
                    WasteVisualShape.Jar,
                    new Color(0.62f, 0.9f, 0.84f),
                    new Color(0.2f, 0.56f, 0.5f),
                    0.96f,
                    0.88f,
                    0.08f,
                    "Glassware stays in the glass stream when empty.",
                    LoadPrefab("Assets/LowpolyDrinkGlasses/Prefabs/Collection_6.prefab"),
                    Vector3.zero,
                    Vector3.zero,
                    Vector3.one * 0.18f),
                new WasteItemDefinition(
                    "glass_tall",
                    "Tall Glass",
                    RecycleCategory.Glass,
                    RecycleCategory.Plastic,
                    WasteVisualShape.Jar,
                    new Color(0.56f, 0.88f, 0.82f),
                    new Color(0.18f, 0.52f, 0.45f),
                    0.96f,
                    0.88f,
                    0.08f,
                    "Glass items are sorted into the glass bin after use.",
                    LoadPrefab("Assets/LowpolyDrinkGlasses/Prefabs/Collection_8.prefab"),
                    Vector3.zero,
                    Vector3.zero,
                    Vector3.one * 0.18f),
                new WasteItemDefinition(
                    "peach_pit",
                    "Peach Pit",
                    RecycleCategory.Organic,
                    RecycleCategory.PaperCardboard,
                    WasteVisualShape.Scrap,
                    new Color(0.92f, 0.68f, 0.4f),
                    new Color(0.62f, 0.34f, 0.2f),
                    0.9f,
                    0.86f,
                    0.1f,
                    "Fruit scraps belong in the organic bin.",
                    LoadPrefab("Assets/ithappy/Food_FREE/Prefabs/peach_001.prefab"),
                    Vector3.zero,
                    Vector3.zero,
                    Vector3.one * 0.82f),
                new WasteItemDefinition(
                    "tomato_scrap",
                    "Tomato",
                    RecycleCategory.Organic,
                    RecycleCategory.PaperCardboard,
                    WasteVisualShape.Scrap,
                    new Color(0.92f, 0.34f, 0.26f),
                    new Color(0.6f, 0.18f, 0.16f),
                    0.88f,
                    0.86f,
                    0.1f,
                    "Food scraps and produce belong in the organic bin.",
                    LoadPrefab("Assets/ithappy/Food_FREE/Prefabs/tomato_001.prefab"),
                    Vector3.zero,
                    Vector3.zero,
                    Vector3.one * 0.82f),
                new WasteItemDefinition(
                    "carrot_scrap",
                    "Carrot",
                    RecycleCategory.Organic,
                    RecycleCategory.PaperCardboard,
                    WasteVisualShape.Scrap,
                    new Color(0.95f, 0.48f, 0.12f),
                    new Color(0.22f, 0.58f, 0.22f),
                    0.9f,
                    0.86f,
                    0.1f,
                    "Vegetable scraps belong in the organic bin.",
                    LoadPrefab("Assets/ithappy/Food_FREE/Prefabs/carrot_001.prefab"),
                    Vector3.zero,
                    new Vector3(0f, 25f, 0f),
                    Vector3.one * 0.82f),
                new WasteItemDefinition(
                    "burger_leftovers",
                    "Burger Leftovers",
                    RecycleCategory.Organic,
                    RecycleCategory.PaperCardboard,
                    WasteVisualShape.Scrap,
                    new Color(0.74f, 0.42f, 0.18f),
                    new Color(0.22f, 0.52f, 0.18f),
                    0.92f,
                    0.82f,
                    0.14f,
                    "Food leftovers go to organic waste, not paper packaging.",
                    LoadPrefab("Assets/ithappy/Food_FREE/Prefabs/burger_001.prefab"),
                    Vector3.zero,
                    Vector3.zero,
                    Vector3.one * 0.78f),
                new WasteItemDefinition(
                    "donut_leftover",
                    "Donut",
                    RecycleCategory.Organic,
                    RecycleCategory.PaperCardboard,
                    WasteVisualShape.Scrap,
                    new Color(0.78f, 0.46f, 0.26f),
                    new Color(0.95f, 0.62f, 0.78f),
                    0.86f,
                    0.82f,
                    0.14f,
                    "Food waste belongs in the organic bin even when it looks like a packaged snack.",
                    LoadPrefab("Assets/ithappy/Food_FREE/Prefabs/donut_001.prefab"),
                    Vector3.zero,
                    Vector3.zero,
                    Vector3.one * 0.8f),
                new WasteItemDefinition(
                    "sandwich_leftover",
                    "Sandwich",
                    RecycleCategory.Organic,
                    RecycleCategory.PaperCardboard,
                    WasteVisualShape.Scrap,
                    new Color(0.86f, 0.68f, 0.38f),
                    new Color(0.25f, 0.55f, 0.22f),
                    0.92f,
                    0.84f,
                    0.12f,
                    "Leftover food goes to the organic stream.",
                    LoadPrefab("Assets/ithappy/Food_FREE/Prefabs/sandwich_001.prefab"),
                    Vector3.zero,
                    new Vector3(0f, 12f, 0f),
                    Vector3.one * 0.78f),
                new WasteItemDefinition(
                    "fish_leftover",
                    "Fish Leftover",
                    RecycleCategory.Organic,
                    RecycleCategory.Glass,
                    WasteVisualShape.Scrap,
                    new Color(0.58f, 0.66f, 0.72f),
                    new Color(0.92f, 0.78f, 0.52f),
                    0.9f,
                    0.82f,
                    0.14f,
                    "Food leftovers belong in the organic bin.",
                    LoadPrefab("Assets/ithappy/Food_FREE/Prefabs/fish_001.prefab"),
                    Vector3.zero,
                    new Vector3(0f, 35f, 0f),
                    Vector3.one * 0.78f),
                new WasteItemDefinition(
                    "takeaway_coffee_cup",
                    "Takeaway Coffee Cup",
                    RecycleCategory.Plastic,
                    RecycleCategory.PaperCardboard,
                    WasteVisualShape.Cup,
                    new Color(0.94f, 0.91f, 0.84f),
                    new Color(0.28f, 0.18f, 0.12f),
                    0.9f,
                    0.78f,
                    0.2f,
                    "In this sorting setup, lined takeaway cups are treated as plastic-like mixed packaging.",
                    LoadPrefab("Assets/ithappy/Food_FREE/Prefabs/coffee_001.prefab"),
                    Vector3.zero,
                    Vector3.zero,
                    Vector3.one * 0.78f),
                new WasteItemDefinition(
                    "glass_collection_1",
                    "Glass Cup",
                    RecycleCategory.Glass,
                    RecycleCategory.Plastic,
                    WasteVisualShape.Jar,
                    new Color(0.64f, 0.9f, 0.86f),
                    new Color(0.2f, 0.55f, 0.5f),
                    0.95f,
                    0.88f,
                    0.08f,
                    "Empty glassware belongs in the glass bin.",
                    LoadPrefab("Assets/LowpolyDrinkGlasses/Prefabs/Collection_1.prefab"),
                    Vector3.zero,
                    Vector3.zero,
                    Vector3.one * 0.18f),
                new WasteItemDefinition(
                    "glass_collection_3",
                    "Short Glass",
                    RecycleCategory.Glass,
                    RecycleCategory.Plastic,
                    WasteVisualShape.Jar,
                    new Color(0.58f, 0.88f, 0.86f),
                    new Color(0.18f, 0.5f, 0.47f),
                    0.95f,
                    0.88f,
                    0.08f,
                    "Glass items stay separate from plastic recycling.",
                    LoadPrefab("Assets/LowpolyDrinkGlasses/Prefabs/Collection_3.prefab"),
                    Vector3.zero,
                    Vector3.zero,
                    Vector3.one * 0.18f),
                new WasteItemDefinition(
                    "glass_collection_5",
                    "Wide Glass",
                    RecycleCategory.Glass,
                    RecycleCategory.Plastic,
                    WasteVisualShape.Jar,
                    new Color(0.62f, 0.9f, 0.88f),
                    new Color(0.21f, 0.57f, 0.52f),
                    0.95f,
                    0.88f,
                    0.08f,
                    "Glass belongs in the glass recycling stream.",
                    LoadPrefab("Assets/LowpolyDrinkGlasses/Prefabs/Collection_5.prefab"),
                    Vector3.zero,
                    Vector3.zero,
                    Vector3.one * 0.18f),
                new WasteItemDefinition(
                    "glass_collection_7",
                    "Stem Glass",
                    RecycleCategory.Glass,
                    RecycleCategory.Plastic,
                    WasteVisualShape.Jar,
                    new Color(0.62f, 0.88f, 0.86f),
                    new Color(0.2f, 0.54f, 0.5f),
                    0.95f,
                    0.88f,
                    0.08f,
                    "Empty glass items go into the glass bin.",
                    LoadPrefab("Assets/LowpolyDrinkGlasses/Prefabs/Collection_7.prefab"),
                    Vector3.zero,
                    Vector3.zero,
                    Vector3.one * 0.18f),
                new WasteItemDefinition(
                    "glass_collection_9",
                    "Rounded Glass",
                    RecycleCategory.Glass,
                    RecycleCategory.Plastic,
                    WasteVisualShape.Jar,
                    new Color(0.6f, 0.9f, 0.84f),
                    new Color(0.18f, 0.52f, 0.48f),
                    0.95f,
                    0.88f,
                    0.08f,
                    "Sort glass separately so it can be processed correctly.",
                    LoadPrefab("Assets/LowpolyDrinkGlasses/Prefabs/Collection_9.prefab"),
                    Vector3.zero,
                    Vector3.zero,
                    Vector3.one * 0.18f),
                new WasteItemDefinition(
                    "glass_collection_10",
                    "Clear Glass",
                    RecycleCategory.Glass,
                    RecycleCategory.Plastic,
                    WasteVisualShape.Jar,
                    new Color(0.66f, 0.92f, 0.88f),
                    new Color(0.22f, 0.58f, 0.54f),
                    0.95f,
                    0.88f,
                    0.08f,
                    "Clear glass belongs in the glass bin.",
                    LoadPrefab("Assets/LowpolyDrinkGlasses/Prefabs/Collection_10.prefab"),
                    Vector3.zero,
                    Vector3.zero,
                    Vector3.one * 0.18f)
            };
        }

                private static GameObject LoadPrefab(string assetPath)
                {
            #if UNITY_EDITOR
                    return AssetDatabase.LoadAssetAtPath<GameObject>(assetPath);
            #else
                    return Resources.Load<GameObject>(assetPath);
            #endif
                }
    }
}
